name: scrape-prices

on:
  workflow_dispatch:
  schedule:
    - cron: '15 12 * * *'  # ajusta horario UTC

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_JSON: ${{ secrets.GSHEETS_SA_JSON }}
      OUT_DIR: ./data
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pipeline
        run: python pipeline_ingesta.py
